server:
  port: 8086

spring:
  application:
    name: search-service
  config:
    import:
      - optional:nacos:shared-infra.yaml?group=COMMON
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:18848
        enabled: true
      config:
        server-addr: ${NACOS_HOST:localhost}:18848

dubbo:
  application:
    name: search-service
    qos-enable: false
  registry:
    address: nacos://${NACOS_HOST:localhost}:18848
  protocol:
    name: tri
    port: 20886

elasticsearch:
  host: ${ES_HOST:localhost}
  port: ${ES_PORT:9200}
