server:
  port: 8083

spring:
  application:
    name: note-service
  cassandra:
    keyspace-name: notes
    contact-points: localhost
    port: 19042
    local-datacenter: datacenter1
    schema-action: NONE
    request:
      timeout: 5s
  data:
    redis:
      host: localhost
      port: 16379
  datasource:
    url: jdbc:mysql://localhost:13306/live_community?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: note-interaction-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.common
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848

minio:
  endpoint: http://localhost:19000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: notes

dubbo:
  application:
    name: note-service
  registry:
    address: nacos://localhost:18848
  protocol:
    name: tri
    port: 20882
