server:
  port: 8081

spring:
  application:
    name: upload-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848

minio:
  endpoint: http://localhost:19000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: uploads

dubbo:
  application:
    name: upload-service
  registry:
    address: nacos://localhost:18848
  protocol:
    name: tri
    port: 20880
