server:
  port: 8081

spring:
  application:
    name: upload-service
  config:
    import:
      - optional:nacos:shared-infra.yaml?group=COMMON
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:18848
        enabled: true
      config:
        server-addr: ${NACOS_HOST:localhost}:18848

minio:
  endpoint: http://localhost:19000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: uploads

dubbo:
  application:
    name: upload-service
  registry:
    address: nacos://${NACOS_HOST:localhost}:18848
  protocol:
    name: tri
    port: 20880
